### ISSUE TITLE
Problems managing badges

### ISSUE THREAD

**Issue by dracero** [MMDevelopment/moodle-block_credly#1]
I recently installed the Credly Plugin in Moodle 2.7.7+, everything was great but I noted a problem with the badges that I created. I was able to create a badge from Moodle and I saw the badge in Credly but I wasn't able to see the recently ceated badge in Moodle.

Thanks in advance for your help.

**Comment by deds** [comment]
@dracero 

I'm assuming it was through the page where you can view all the badges?  I believe I have a 24-hour period caching  the fetched badges.  I do have code to flush them on successful create.  Can you recheck the page after 24-hours?  If they are viewable by then, I will assume it's a bug on the caching code and will review.  Thanks.

**Comment by dracero** [comment]
I checked after 24 hour and remains the same. When I try to grant a badge I
received the message "The system encountered an error trying to grant the
badge."

Thank you for your help.

On Fri, Mar 27, 2015 at 9:29 AM, Deds Castillo notifications@github.com
wrote:

> @dracero https://github.com/dracero
> 
> I'm assuming it was through the page where you can view all the badges? I
> believe I have a 24-hour period caching the fetched badges. I do have code
> to flush them on successful create. Can you recheck the page after
> 24-hours? If they are viewable by then, I will assume it's a bug on the
> caching code and will review. Thanks.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MMDevelopment/moodle-block_credly/issues/1#issuecomment-86927068
> .

## 

Ing. Diego Racero.
  F.I.U.B.A

**Comment by deds** [comment]
What happens if you try and create another badge through the Moodle ui (not directly from within Credly)?

**Comment by dracero** [comment]
I created a badge from Moodle user interface, I see the recently created
badge in Credly but I'm not able to see It in Moodle.

On Fri, Mar 27, 2015 at 10:02 AM, Deds Castillo notifications@github.com
wrote:

> What happens if you try and create another badge through the Moodle ui
> (not directly from within Credly)?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MMDevelopment/moodle-block_credly/issues/1#issuecomment-86933808
> .

## 

Ing. Diego Racero.
  F.I.U.B.A

**Comment by deds** [comment]
Ok. So everything is functioning on the credentials side since you're able to create a badge.  Please  manually delete the entries on the block_credly_cache table and try managing the badges again to check if you can now see in Moodle.

**Comment by dracero** [comment]
I just deleted the table but everything remains equal.

Any clue?

Thanks in advance.

On Fri, Mar 27, 2015 at 10:19 AM, Deds Castillo notifications@github.com
wrote:

> Ok. So everything is functioning on the credentials side since you're able
> to create a badge. Please manually delete the entries on the
> block_credly_cache table and try managing the badges again to check if you
> can now see in Moodle.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MMDevelopment/moodle-block_credly/issues/1#issuecomment-86937710
> .

## 

Ing. Diego Racero.
  F.I.U.B.A

**Comment by deds** [comment]
I can't suggest anything else right now.  If you're ok with giving me access to the moodle instance then I can help take a look.

**Comment by dracero** [comment]
Deds, I really will appreciate if you take a look at my server's
configuration. The URL is http://cead.fi.uba.ar/m27/moodle

**\* credentials removed ***

It is a trial server where we test all the new plugins. We are very exited
about Credly plugin because It will be a way to put our server on SNS.

Due to easter holiday the server will be down, but It is on line again on
Monday monrning.

Thanks in advance for your help

Happy easter!!!

On Thu, Apr 2, 2015 at 11:43 AM, Deds Castillo notifications@github.com
wrote:

> I can't suggest anything else right now. If you're ok with giving me
> access to the moodle instance then I can help take a look.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MMDevelopment/moodle-block_credly/issues/1#issuecomment-88932692
> .

## 

Ing. Diego Racero.
  F.I.U.B.A

**Comment by dracero** [comment]
Hi Ded, I perform a clean installation previusly unistalling Credly and now
everything work fine.

Thank yuo very much for your help.

On Thu, Apr 2, 2015 at 8:00 PM, Diego Racero diego.racero@gmail.com wrote:

> Deds, I really will appreciate if you take a look at my server's
> configuration. The URL is http://cead.fi.uba.ar/m27/moodle
> 
> user:admin
> password: Moodle2.7
> 
> It is a trial server where we test all the new plugins. We are very exited
> about Credly plugin because It will be a way to put our server on SNS.
> 
> Due to easter holiday the server will be down, but It is on line again on
> Monday monrning.
> 
> Thanks in advance for your help
> 
> Happy easter!!!
> 
> On Thu, Apr 2, 2015 at 11:43 AM, Deds Castillo notifications@github.com
> wrote:
> 
> > I can't suggest anything else right now. If you're ok with giving me
> > access to the moodle instance then I can help take a look.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/MMDevelopment/moodle-block_credly/issues/1#issuecomment-88932692
> > .
> 
> ## 
> 
> Ing. Diego Racero.
>   F.I.U.B.A

## 

Ing. Diego Racero.
  F.I.U.B.A

**Comment by deds** [comment]
dracero, that's good to hear.  I apologize as I wasn't able to look at it this week.  Busy week due to the tax schedule here. :)
