### ISSUE TITLE
problem with grant and manage badges

### ISSUE THREAD

**Issue by drroad09** [MMDevelopment/moodle-block_credly#3]
Hello Deds,

Thank you very much for creating moodle block to work with Credly. We were able to set it up on Moodle. However every time we try to add new badges, the value on mdl_block_credly_cache would get overwritten by null. This results in having nothing to display when we try to grant the badge to the users. If you have time, could you take a look at the codes please? Much appreciate.

**Comment by deds** [comment]
@drroad09 I was recently made aware of a problem where the credentials being used are that of an individual but the intention is to grant badges belonging to an institution.  This results in the same behavior as what you are seeing.  Would this be your scenario as well?

**Comment by drroad09** [comment]
Hi Deds. Yes, that is the situation. We created an individual account on Credly, got the API, added that to Moodle. But when we log in to Moodle using the admin account (different account from the one we use for Credly), and try adding new badges that is when we see null value in mdl_block_credly_cache. Is there a work around? Thank you very much for your help.

**Comment by deds** [comment]
Hi @drroad09 that sounds like a different case.  I'm working on a new version but I'm still waiting for some feedback from the Credly folks.  The workaround I can think of right now is for you to disable the cache.  Edit the file lib.php inside the block and have block_credly_get_from_cache function return false.  Just adding a

`return false;`

as the first line of that function should work.  If the problem still persists then this is most likely an api error.  As interim debugging you can just add an

`error_log($response);`

inside the function block_credly_call_api (lib.php) just after the call to curl_exec.  Then just monitor your error log for the returned response.

**Comment by drroad09** [comment]
Hi Deds. I disabled the cache in lib.php. 
`function block_credly_get_from_cache($userid=0, $itemtype) {
	
	return false;
	/*
    global $DB;
    $rec = $DB->get_record('block_credly_cache', array('userid' => $userid, 'itemtype' => $itemtype));
    return $rec;
	*/
}`

but still not working. Nothing shows after adding the badge. Should I install Credly block again? I also do not see the errors after adding error_log($response); inside block_credly_call_api(lib.php). Thank you!

**Comment by deds** [comment]
@drroad09 if the response looks valid then yes, it might be the manager vs organization issue during badge creation.  I'm still waiting on a response from the credly team so that I get proper access before I can correct the code.

**Comment by drroad09** [comment]
Great! Thank you very much for all your helps Deds.

**Comment by deds** [comment]
@drroad09 I just updated the code to support organizations and turn off caching by default.  Please check if it's now working for your.

**Comment by drroad09** [comment]
Hello Deds. Thank you very much. The update codes worked!!! You are awesome!

**Comment by deds** [comment]
Good to know this worked out for you.  Closing this now.
